### PR TITLE
API Changes

### PR DESCRIPTION
**Pull request by dralley**
The schema looks like this:

```
"_content": {
    "file": "/pulp/api/v3/content/file/files/?repository_version=..."
},
"_content_added": {
    "file": "/pulp/api/v3/content/file/files/?repository_version_added=..."
},
"_content_removed": {}
```

Change the get_*content() functions to return a dictionary of types
matched to the respective list of content of that type.

Fix the get_artifact_paths() function to use those new functions
properly.

### CODE REVIEW

**Comment by dralley** [comment]
@kersommoura , PyLint doesn't seem to distinguish between constants and functions defined as variables.  What would you recommend I do, put in ignores for the warnings or rewrite this code somehow?

**Comment by dralley** [comment]
The rationale for using defaultdicts instead of normal dicts in those few places is so that you don't have to deal with a KeyError when using the get_*_content functions with a type that doesn't exist in the resultant dict.  

For example you might want to do this

```
self.assertEqual(len(get_added_content(repo)['python']), 0)
```

If there are no packages in the added content, then this would raise a KeyError.  But with defaultdict it returns an empty list, and the test works fine.

**Comment by kersommoura** [comment]
@dralley, I will take a look into this right now.

**Comment by kersommoura** [comment]
Those changes will change how pulp-smash parses some responses from Pulp 3. However, those changes are necessary since Pulp API itself is changing as well.

Those changes were discussed on pulp-dev mail list.

**Comment by kersommoura** [comment]
See: http://pylint.pycqa.org/en/latest/user_guide/options.html#default-behavior

**Comment by kersommoura** [comment]
Those changes were tested with the new API layout. 

See: https://github.com/pulp/pulp_file/pull/133/files

**Comment by kersommoura** [comment]
@dralley, I reviewed those changes related to the functional tests. I left minor comments.

**Pull request merged**
