### PR TITLE
Add new API response handler called page_handler

### PR DESCRIPTION
**Pull request by Ichimonji10**
This response handler is similar to `json_handler`, but:

* It is only compatible with Pulp 3.
* If it detects that the response is a page, it will walk through all
  pages of results, collect the results into a single list, and return
  that list.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Tested against Pulp 2.16.1 nightly with:

```bash
for package in pulp_smash.tests.pulp2.{platform,python}.api_v2; do
    python -m unittest discover -fv "$package"
done
```

Tested against Pulp 3 from-source with:

```bash
python -m unittest discover -fv pulp_smash.tests.pulp3.file
```

**Comment by kersommoura** [comment]
Related to https://github.com/PulpQE/pulp-smash/issues/918

**Comment by Ichimonji10** [comment]
Adding unit tests.

**Comment by Ichimonji10** [comment]
Unit tests added. Re-tested against Pulp 2 and 3 VMs.

**Comment by kersommoura** [comment]
I explored the new `response_handler`. For instance, for Pulp 3, I replaced the `json_handler` to `page_hander`.

Besides that, I forced the pagination to be triggered changing a parameter in Pulp 3 settings, and I ran a few other tests using `json_handler` and `page_handler`.

The new `response_handler` will be very helpful for Pulp 3 tests.

Good job @Ichimonji10 !

**Comment by Ichimonji10** [comment]
Good catch. Updated.

**Pull request merged**
