### PR TITLE
Test SELinux filesystem labels

### PR DESCRIPTION
**Pull request by Ichimonji10**
Add test case `FileLabelsTestCase` in module
`pulp_smash.tests.platform.cli.test_selinux`.

Fix: https://github.com/PulpQE/pulp-smash/issues/442

### CODE REVIEW

**Comment by Ichimonji10** [comment]
@dkliban: This test fails like so:

```console
$ python -m unittest pulp_smash.tests.platform.cli.test_selinux.FileLabelsTestCase
..
======================================================================
FAIL: test_pulp_server_fc (pulp_smash.tests.platform.cli.test_selinux.FileLabelsTestCase) [('/var/lib/pulp', ':object_r:httpd_sys_rw_content_t:s0')]
Test files listed in ``pulp-server.fc``.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/tests/platform/cli/test_selinux.py", line 175, in test_pulp_server_fc
    self._do_test(file_, label, True)
  File "/home/ichimonji10/code/pulp-smash/pulp_smash/tests/platform/cli/test_selinux.py", line 147, in _do_test
    self.assertEqual(file_label, label, getfattr_file)
AssertionError: ':object_r:pulp_cert_t:s0' != ':object_r:httpd_sys_rw_content_t:s0'
- :object_r:pulp_cert_t:s0
+ :object_r:httpd_sys_rw_content_t:s0
 : ('var/lib/pulp/static/rsa_pub.key',)

----------------------------------------------------------------------
Ran 3 tests in 1.532s

FAILED (failures=1)
```

Can you provide any input?

**Comment by Ichimonji10** [comment]
@elyezer This test makes use of the `getfattr` executable. This executable is available out of the box on Fedora, but needs to be installed on RHEL. Can a step to install the `attr` package be added to pulp_packaging or some other appropriate script?

**Comment by elyezer** [comment]
> @elyezer This test makes use of the getfattr executable. This executable is available out of the box on Fedora, but needs to be installed on RHEL. Can a step to install the attr package be added to pulp_packaging or some other appropriate script?

Definitely, I will handle that for you.

**Comment by Ichimonji10** [comment]
By the way, I checked, and the file is called `attr` on Fedora 23, Fedora 24, RHEL 6.8 and RHEL 7.3. No platform-specific logic should be necessary.

**Comment by Ichimonji10** [comment]
Rebased. I also made the minor change of moving a comment.

**Comment by dkliban** [comment]
@Ichimonji10 The pulp_cert_t type makes sense. Without it, SELinux would not allow Pulp to use this file as a cert. However, we should probably have an explicit statement in our SELinux policy that says this file needs to have this security context type. I suspect running restorecon would change the security context type to httpd_sys_rw_content_t.

**Comment by Ichimonji10** [comment]
@dkliban Running `restorecon /var/lib/pulp/static/rsa_pub.key` sets the file's context to `unconfined_u:object_r:pulp_cert_t:s0`. This context is expected by Pulp Smash and is listed here: https://github.com/pulp/pulp/tree/master/server/selinux/server

**Comment by Ichimonji10** [comment]
Test now passes. See: https://pulp.plan.io/issues/2508

**Pull request merged**
