### PR TITLE
[WIP] Integration tests for resource manager failover

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by elyezer** [comment]
Before I start to review and test these changes I need some information:

* What are the Pulp versions that these tests should run against?
* We talked about the need of a machine with Pulp Agent and another with Pulp Server. You commented about the setup for the Pulp Agent and I would like to know if there is some documentation about it? I mean, is there a Pulp documentation explaining all the steps to get a separated Pulp Agent?

These tests should be skipped if there is not `pulp agent` section on the Pulp Smash settings, @Ichimonji10 have created https://github.com/PulpQE/pulp-smash/compare/master...Ichimonji10:test-agent-demo which shows how to do that, can you please incorporate those changes?

**Comment by dralley** [comment]
@elyezer 

* The feature PR is currently not merged into master yet, it's still awaiting review.  The PR is to master, and the feature will likely go into 2.10.  I'll try to get someone to get it reviewed and merged soon.

* We want 2 boxes with pulp-server installed, but we want to configure the pulp-server installation on the 2nd box to connect to the Qpid broker and MongoDB instance running on the 1st box.  I'll want to double check that there are no extra steps beyond this, but I know that you will need to:

    1.  Make sure ports 27017 and 5672 are open
    2.  Edit /etc/pulp/server.conf on box 2
         * Under the ```[database]``` section, the ```seeds``` parameter should be set to <<IP Address of the 1st machine>>:27017
          * Under the ```[tasks]``` section, ```"broker_url``` should be set to ```qpid://<<IP Address of the first machine>>```
    3.  Add a section to the pulp_smash config with the IP address of box 2

**Comment by elyezer** [comment]
Closes #343

**Comment by dralley** [comment]
@Ichimonji10 should we just close this PR?

**Comment by Ichimonji10** [comment]
@dralley I have no opinion. I don't mind leaving this open, but closing this would clean things up. This PR requires multiple hosts for test infrastructure, and we're only slightly closer to that goal than we were when this PR was created.

**Comment by dralley** [comment]
Agreed, and I don't think at this point that it will happen in Pulp 2's lifecycle.  The change velocity for Pulp 2 is going to continue to decrease which will also decrease the utility of these tests, as the likelihood of breakage will be very low.

I'm going to close this for now.

**Pull request closed without merging**
