### PR TITLE
Add test of scheduled install on pulp-consumer

### PR DESCRIPTION
**Pull request by kdelee**
NOTE: Packages necessary for pulp-consumer to function must be installed
for this test run. 

I will be filing an issue in [pulp/pulp_packaging](https://github.com/pulp/pulp_packaging) and linking it here momentarily.

closes issue #611

### CODE REVIEW

**Comment by kdelee** [comment]
See pulp_packaging issue [#2845](https://pulp.plan.io/issues/2845) for story of what Jenkins user would need to get tests like this one running

**Comment by Ichimonji10** [comment]
This PR is temporarily being set aside. A proper solution will be nasty and gnarly. It can be done, but I think it's appropriate to come back to it with a little more experience in hand.

**Comment by kdelee** [comment]
@Ichimonji10 
Sounds good.

**Comment by Ichimonji10** [comment]
Well, unless you're really raring to keep on working at this one. I won't stop you. :wink: Take the above as a suggestion, not a command.

**Comment by kdelee** [comment]
I think I'm going to work on [#2845](https://pulp.plan.io/issues/2845), which is a blocker for this, before I get back to refactoring this code.

**Pull request closed without merging**
