### PR TITLE
Added signatures check tests in rpm repositories

### PR DESCRIPTION
**Pull request by emmawu**
**Added 2 test files for signature check on packages and rpm repositories:**
- pulp_smash/tests/rpm/api_v2/test_package_signature.py (Pulp #1156)
- pulp_smash/tests/rpm/api_v2/test_repo_signature.py (Pulp #1991)

**Updated test fixture links:**
- pulp_smash/constants.py

Note: The new fixture links are valid only after PulpQE/pulp-fixtures are updated (https://github.com/PulpQE/pulp-fixtures/pull/17)

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Please make sure that this pull request satisfies the [code standards](http://pulp-smash.readthedocs.io/en/latest/about.html#code-standards).

First, make sure that this commit passes the linters. You can run them locally with `make all`, or let Travis do the work for you. Note that flake8 version 3 introduced some breakage. I recommend that you base your pull request on the latest version of the Pulp Smash code, so that you can take advantage of the workaround implemented by https://github.com/PulpQE/pulp-smash/pull/338.

Second, make sure that the tests in this pull request pass. I have doubts, based on a combination of syntax errors and lines such as this:

```python
    "empty_allowed": {
        "allow  _keys": [],  # spurious space
        "allow_unsigned": None
    },
```

By the way, I understand that the tests introduced by this pull request depends on the fixtures introduced by https://github.com/PulpQE/pulp-fixtures/pull/17. You can simulate the presence of those fixtures by generating them, `cd`ing into the right directory, executing `python3 -m http.server`, and placing `http://localhost:8000` in `pulp_smash/constants.py`.

Third, please make sure that each commit addresses a single issue. There's at least two significant changes being made by this pull request. First, several existing constants are being renamed, and second, quite a bit of new test code is being added.

Why does this matter? In short, because having a clean commit history makes it easy to understand what's happened, to undo changes, to use `git blame`, etc. We even use the commit history to auto-generate commit messages for [releases](https://github.com/PulpQE/pulp-smash/releases). 

Here's what the current commit history looks like to me:

screenshot_2016-07-26_13-40-18

**Comment by Ichimonji10** [comment]
The needed fixtures are now available. See [here](https://repos.fedorapeople.org/pulp/pulp/fixtures/).

**Comment by emmawu** [comment]
I re-pushed the commits for this PR. Now it consists of only 2 commits. 
The first commit is to update test fixtures and the second commit is to add/update tests

Before submitting the commits, I ran `make all` to validate the code. But it failed at lint-pylint.
> ************* Module pulp_smash.cli
E:169, 0: Bad option value u'redefined-variable-type' (bad-option-value)
************* Module tests.test_config
E: 12, 0: Bad option value u'C0411' (bad-option-value)
E: 12, 0: Bad option value u'E0401' (bad-option-value)
Makefile:36: recipe for target 'lint-pylint' failed

Those 2 modules are not in my commits. I don't know how I could fix it or bypass it..
And I ran following targets in 'all' one by one manually: 
 `test-coverage lint-flake8 lint-pylint docs-clean docs-html package-clean package`
All targets passed except the lint-pylint due to the bad-option-value error in pulp_smash.cli and tests.test_config modules.

Here are the version of the python and pylint I ran test:
- Python 2.7.11
- Pylint 1.4.3

Could you please advise me what I should do to this?
Thank you very much.

**Comment by ipanova** [comment]
This testcase should be updated to reflect changes done  in  #1991
please take as reference docs mentioned in this PR https://github.com/pulp/pulp_rpm/pull/938
and this pulp-smash issue reported https://github.com/PulpQE/pulp-smash/issues/347

**Comment by emmawu** [comment]
Thanks. @emilyzheng will follow up and update theses test cases for the signature-check.

**Comment by Ichimonji10** [comment]
> Here are the version of the python and pylint I ran test:
>
>     Python 2.7.11
>     Pylint 1.4.3
>
> Could you please advise me what I should do to this?
> Thank you very much.

Pylint 1.4.3 is old. It was [released](https://github.com/PyCQA/pylint/releases/tag/pylint-1.4.3) on March 14, 2015. The solution to this issue is to use newer Python packages. Are you using the packages provided by your package manager? I recommend that you avoid the packages provided by your package manager, and use a Python virtualenv instead. Thankfully, it's easy to use a virtualenv, as Pulp Smash and all of its dependencies are pure Python packages. The procedure for doing this is outlined in Pulp Smash's documentation, notably the [Installation](http://pulp-smash.readthedocs.io/en/latest/installation.html) section. If using Python 2, it goes like this:

```sh
virtualenv -p python2 env
source env/bin/activate
git clone https://github.com/PulpQE/pulp-smash.git
cd pulp-smash
pip install -r requirements.txt -r requirements-dev.txt
```

All of Pulp Smash's dependencies are installed into the virtualenv, and Pulp Smash itself is installed in "develop mode," meaning that when changes are made to the Pulp Smash source code, those changes immediately show up in installed package.

To exit the virtualenv, run `deactivate`. At this point, the virtualenv can be destroyed with `rm -rf env`. For more information, read the fantastic documentation.

By the way, Travis' logs show which packages are installed into its virtualenv. See, for example, https://travis-ci.org/PulpQE/pulp-smash/jobs/148656163

**Comment by Ichimonji10** [comment]
I've rebased and merged the first commit as ac771431083c31dee163a25d85ae275ad635869c, with a follow-up commit of 9e7b354ff27c9079fc72499aab732ab5c5b14e49. See: https://github.com/PulpQE/pulp-smash/commits/master.

None of the changes in the follow-up commit should in any way affect the tests added by the second commit. Getting up-to-date is as simple as:

```bash
git fetch --all
git checkout signature-check
git rebase upstream/master
```

Git will automatically detect that the first of two commits in this branch is already in `upstream/master`, and it will only move the second commit. Things will change from this:

screenshot_2016-08-09_16-14-01

To this:

screenshot_2016-08-09_16-14-22

Cool, hunh?

On a related note, https://github.com/PulpQE/pulp-fixtures/pull/24 has been merged. As a result, it should be valid to make the following change:

```diff
diff --git a/pulp_smash/tests/rpm/api_v2/test_repo_signature.py b/pulp_smash/tests/rpm/api_v2/test_repo_signature.py
index 06c4023..7469e6a 100644
--- a/pulp_smash/tests/rpm/api_v2/test_repo_signature.py
+++ b/pulp_smash/tests/rpm/api_v2/test_repo_signature.py
@@ -43,7 +43,7 @@ _REPO_CONFIGS = {
         'allow_unsigned': None
     },
     'matching_allowed': {
-        'allow_keys': ['260f3a2b', 'f78fb195'],
+        'allow_keys': ['269d9d98'],
         'allow_unsigned': None
     },
     'not_matching_allowed': {
@@ -63,7 +63,21 @@ _REPO_CONFIGS = {
         'allow_unsigned': True
     },
 }
-"""A dict of different combinations of repo importer configurations."""
+"""A dict of different combinations of repo importer configurations.
+
+The valid key ID, above, comes from Pulp Fixtures. To calculate a new key ID,
+find the public key used by Pulp Fixtures (it should be in the Pulp Fixtures
+source code repository) and use GnuPG to examine it::
+
+    $ gpg "$public_key_file"
+    pub   rsa2048 2016-08-05 [SC]
+          6EDF301256480B9B801EBA3D05A5E6DA269D9D98
+    uid           Pulp QE
+    sub   rsa2048 2016-08-05 [E]
+
+The last 32 bits (8 characters) of the key ID are what Pulp wants — in this
+case, 269D9D98.
+"""
 
 
 def _gen_repo_with_sig_options(allow_keys=None, allow_unsigned=None):
```

**Comment by Ichimonji10** [comment]
@emmawu, I've reviewed `pulp_smash/tests/rpm/api_v2/test_package_signature.py` and created a follow-up commit for that new test module. There's no need to update it further. I'll start reviewing `test_repo_signature.py` tomorrow.

**Comment by Ichimonji10** [comment]
Merged as 81c509f33eff43c726ee4509a2d9b1ad93cd8827, with a follow-up commit of f663905cf2215404045a85966a72b4a1f7ba3e5b.

Please take note of some of the changes made in the follow-up commit. Most notably, the attribute names exposed by Pulp are different from what was originally listed in the pulp.plan.io issues. See:

* https://pulp.plan.io/issues/1156#note-29
* https://pulp.plan.io/issues/1991#note-31

**Pull request closed without merging**
