### PR TITLE
Document best practices for collaboration

### LINKED ISSUE #131: Document best practices for collaboration
Let's create a wiki/document describing 'the rules of engagement', best practices for collaboration with this project. What do we expect from pull requests, issues, etc created by those who want to collaborate with the project, as well as what they should expect from us.

### PR DESCRIPTION
**Pull request by Ichimonji10**
Fix #131.

Rewrite `docs/about.rst`, with a focus on the "Contributing" section.

### CODE REVIEW

**Comment by elyezer** [comment]
LGTM

**Comment by Ichimonji10** [comment]
@mhrivnak @omaciel Mind taking a look?

**Comment by omaciel** [comment]
@Ichimonji10 LGTM2

**Comment by mhrivnak** [comment]
LGTM3 with one suggestion. As-is, this is a good list of rules and policies that protect the project and make it easier to receive and accept contributions, placing the primary burden on the contributor. The "Contributing" section would benefit from some balance now by adding information that makes the contributor's job easier.

How do I get started? What should a basic test case look like? How are things organized? Are there some utility functions I can use to make test writing easier?

This is fine to address in a different PR, but I wanted to at least get the idea out while this discussion is underway.

**Comment by Ichimonji10** [comment]
:+1:

**Pull request merged**
