### PR TITLE
Drop Python 2 support

### LINKED ISSUE #356: Remove all Python 2 related compatibility
On #332 we agreed that we are able to drop Python 2 support for Pulp Smash. Here is the plan to actually get that done:

- [ ] Drop the compat module
- [ ] Update the imports to reflect the removal of the compat module
- [ ] Drop unittest2 in favor of Python 3's unitttest module and update the code
- [ ] Drop mock in favor of the builtin Python 3's mock
- [ ] Update the `setup.py` file
- [ ] Update the documentation
- [ ] Drop `__future__` imports

### PR DESCRIPTION
**Pull request by elyezer**
Pulp Smash only support Python 3.4+ now.

Do the following to drop Python 2 support:

* Remove pulp_smash.compat module.
* Update compat module related imports to proper Python 3 modules.
* Update Makefile due to the removal of pulp_smash.compat module
* Drop unittest2 package in favor of Python 3's unittest module.
* Drop mock package in favor of Python 3's unittest.mock module.
* Update setup.py to reflect the packages drop and Python 3 only support.
* Update .travis.yml to the current the Python supported versions.
* Update documentation.

Close #356

### CODE REVIEW

**Comment by seandst** [comment]
Squeeeeeeeeee

**Comment by Ichimonji10** [comment]
Can we update the python shebangs?

```console
$ git grep '#!'
pulp_smash/tests/platform/api_v2/test_login.py:#     #!/usr/bin/env python
scripts/gen_api_docs.sh:#!/usr/bin/env bash
scripts/release.sh:#!/bin/bash
scripts/run_functional_tests.py:#!/usr/bin/env python
setup.py:#!/usr/bin/env python
```

**Comment by elyezer** [comment]
> Can we update the python shebangs?

I am glad you brought this, I though on updating them to look for python3 instead of just python that on OS level maps to python2 and on a Python 3 virtualenv maps to python3. With that in mind and having python as python3 on virtualenv I decided to leave as is. Thinking about that once again and having in mind that explicit is better than implicit I think it worth updating the shebangs.

**Comment by Ichimonji10** [comment]
For what it's worth, pythonN should be available from within virtualenvs.

```console
$ pyvenv env
$ source env/bin/activate
$ which python
/home/ichimonji10/tmp/env/bin/python
$ which python2
/usr/bin/python2
$ which python3
/home/ichimonji10/tmp/env/bin/python3
```

**Comment by elyezer** [comment]
Yes, just decided to go implicit which was not the best call.

**Comment by Ichimonji10** [comment]
/me shrugs. That's what PR reviews are for. :smile:

**Comment by elyezer** [comment]
After the changes:

```
pulp_smash/tests/platform/api_v2/test_login.py:#     #!/usr/bin/env python3
scripts/gen_api_docs.sh:#!/usr/bin/env bash
scripts/release.sh:#!/bin/bash
scripts/run_functional_tests.py:#!/usr/bin/env python3
setup.py:#!/usr/bin/env python3
```

**Comment by Ichimonji10** [comment]
As noted earlier, I can successfully execute the test suite. (OK, there was one set of failures. But I think that's due to changes in pulp.plan.io bug states, not this commit.) This commit also addresses all of the to-do items in #356.

**Pull request merged**
