### PR TITLE
Remove Pulp 3 tests and content-specific constants

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by dralley** [comment]
PR moving constants to Pulp-2-Tests is here https://github.com/PulpQE/Pulp-2-Tests/pull/5

**Comment by Ichimonji10** [comment]
This will make it much easier to avoid changing Pulp Smash's major version.

**Comment by Ichimonji10** [comment]
This PR introduces a documentation compilation error. Please fix:

```diff
diff --git a/tests/__init__.py b/tests/__init__.py
index fc03626..8b6c546 100644
--- a/tests/__init__.py
+++ b/tests/__init__.py
@@ -3,6 +3,4 @@
 
 This package and its sub-packages contain tests for Pulp Smash. These tests
 verify that Pulp Smash's internal functions and libraries function correctly.
-
-These tests are entirely different from the tests in :mod:`pulp_smash.tests`.
 """
```

Discovered by locally executing `make all`.

**Comment by dralley** [comment]
@Ichimonji10 fixed

**Comment by Ichimonji10** [comment]
I think this is now a candidate for being merged, as https://github.com/PulpQE/Pulp-2-Tests/pull/8 has been merged. I'll let @dralley make the call, though.

**Comment by dralley** [comment]
@Ichimonji10 it can be merged as soon as the PRs against Pulp and Pulp File get merged, which are still waiting for review.  Also I need to test something before making the CI PR changes.

**Comment by Ichimonji10** [comment]
I take it that Pulp and Pulp File and/or the CI systems install Pulp Smash from source? If so, this is a case where installing from PyPI is beneficial. The next release of Pulp Smash following this PR will bump the X version number.

**Pull request merged**
