### PR TITLE
Replaced two separate identical functions with one function in a common utils file

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by elyezer** [comment]
It looks good to me, do you mind adding the new module to the documentation?

Take a look at https://github.com/PulpQE/pulp-smash/pull/308/files for reference.

**Comment by elyezer** [comment]
@dralley this is really good, thank you.

**Comment by Ichimonji10** [comment]
:+1:

**Comment by danuzclaudes** [comment]
:tada:

**Pull request merged**
