### PR TITLE
Update tests for `<reboot_suggested>` XML element

### PR DESCRIPTION
**Pull request by Ichimonji10**
According to Pulp issue 2032, [1] if an erratum uploaded to Pulp doesn't
suggest a reboot, then the `updateinfo.xml` file published by Pulp
should omit the `<reboot_suggested>` element. Update the relevant test
accordingly.

Thanks to @goosemania for help with making this fix.

[1] https://pulp.plan.io/issues/2032

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Successfully tested against Pulp 2.8.5 and master. I'll comment here again if I test against Pulp 2.8.6.

**Comment by Ichimonji10** [comment]
This should fix one test failure for each element of our Pulp 2.9 test matrix. In total, that should be four failures.

**Comment by danuzclaudes** [comment]
Test fails under 2.9.0b1. And here's the test result:

```
    [vagrant@dev pulp-smash]$ python -m unittest pulp_smash.tests.rpm
.api_v2.test_updateinfo
    .....F.....
    ======================================================================
    FAIL: test_reboot_not_suggested (pulp_smash.tests.rpm.api_v2.
test_updateinfo.UpdateInfoTestCase)
    Assert the update info tree does not suggest a spurious reboot.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "pulp_smash/tests/rpm/api_v2/test_updateinfo.py", line 238,
in test_reboot_not_suggested
        self.assertEqual(len(reboot_elements), 0, reboot_elements)
    AssertionError: 1 != 0 : [<Element 'reboot_suggested' at 0x7fc9e2df1750>]
     
    ----------------------------------------------------------------------
    Ran 11 tests in 38.064s
     
    FAILED (failures=1)
```

**Comment by Ichimonji10** [comment]
I've updated this pull request to better detail what's wrong. Pulp Smash now produces the following error message when targeting Pulp 2.8.6:

```
(pulp-smash2) [ichimonji10@beech:pulp-smash]$ python -m unittest2 pulp_smash.tests.rpm.api_v2.test_updateinfo.UpdateInfoTestCase
...F.....
======================================================================
FAIL: test_reboot_not_suggested (pulp_smash.tests.rpm.api_v2.test_updateinfo.UpdateInfoTestCase)
Assert the update info tree does not suggest a spurious reboot.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pulp_smash/tests/rpm/api_v2/test_updateinfo.py", line 243, in test_reboot_not_suggested
    [ElementTree.tostring(elem) for elem in reboot_elements],
AssertionError: 1 != 0 : ['<reboot_suggested>False</reboot_suggested>']
```

This error indicates that the Pulp issue targeted by this test fails. I've re-opened the issue. See [here](https://pulp.plan.io/issues/2032#note-11).

This test now passes against Pulp 2.8.6 and master.

**Comment by Ichimonji10** [comment]
Thanks for the feedback, @danuzclaudes. You've helped me really polish this PR.

**Pull request merged**
