### PR TITLE
Make all `gen_` functions to accept `**kwargs`

### PR DESCRIPTION
**Pull request by rochacbruno**
Making `gen_` functions to accept `kwargs` allows the customization
of generated dict. e.g: `repo = gen_repo(name='foo')`

### CODE REVIEW

**Comment by rochacbruno** [comment]
@Ichimonji10 Python 3.4 doesn't have the `**kwargs` support for dicts. I can change it to use `.update` instead but the code will be more verbose.

Do we really need Python 3.4 support?

**Comment by Ichimonji10** [comment]
Supporting Python 3.4 lets Pulp Smash run natively on RHEL 7. Being able to use `{..., **kwargs}` is nice, but it seems less important than supporting RHEL 7. Please use `.update`.

**Comment by dralley** [comment]
I thought we are using SCL to get Python 3 on RHEL?  If so, can we not simply upgrade the SCL to Python 3.6, which is what is being used in ```pulp/devel```?

Or does RHEL 7 include Python 3 natively now?  I might be behind the times.

**Comment by Ichimonji10** [comment]
The RHEL 7 repositories provide Python 3.4. The SCLs provide Python 3.5 and 3.6, but configuring and using SCLs is a non-trivial task.

**Comment by dralley** [comment]
Cool, I didn't know 3.4 was available nowadays.  Thanks.

**Comment by Ichimonji10** [comment]
By the way, you're correct that we *are* using SCLs to provide Python 3.6 on RHEL. But that's because Pulp 3 requires Python 3.5 or newer.

**Comment by rochacbruno** [comment]
@Ichimonji10 made it compatible with Python 3.4, Travis is passing (the coverage decrease is unrelated)

**Comment by Ichimonji10** [comment]
LGTM. Please squash the two commits into one. The second commit just modifies how the first commit accomplishes its goal.

**Comment by rochacbruno** [comment]
@Ichimonji10 done! I was used to having it squashed by the "squash and merge" button!

**Comment by kersommoura** [comment]
Rebased and closed as 13df4753536227258a44a856c4fab2eb5d5ce5d5

**Comment by Ichimonji10** [comment]
> @Ichimonji10 done! I was used to having it squashed by the "squash and merge" button!

Fair enough. The commit message wouldn't have made much sense in that case, though. :laughing:

**Pull request closed without merging**
