### PR TITLE
Add util function create_distribution for Pulp 3

### PR DESCRIPTION
**Pull request by kersommoura**
Creating a distribution was modified to be an async task, returning a
202, and task reference. Add a function to ease the creation of
distributions.

See: https://github.com/pulp/pulpcore/pull/6

ref: https://github.com/PulpQE/pulp-smash/issues/1178

### CODE REVIEW

**Comment by kersommoura** [comment]
@rochacbruno, I think a long term solution will be to change our task system to use async code as you suggested on #1178. However this will require a massive overhaul, for the time being I decided to use what we already have in place. 

We already have  a function called `gen_distribution`, I decided to name the new one `create_distribution`. If you have any better naming idea. This change was already tested locally. I will send a PR to pulpcore requesting this one to test once more.

**Comment by rochacbruno** [comment]
@kersommoura 

From the Pulp-Smash user's point of view, I believe we are introducing a source of confusion.

I explain:

To create a repository we do:

`api.post(REPO_PATH, body)`

And the above pattern follows for all other entities.

It is natural that when using Pulp-Smash to automate tasks with speed, we assume that to create distribution we must do:

`api.post(DISTRO_PATH, body)`

But specifically for distribution we have something that goes out of the way.

`pulp3.utils.create_distribution(cfg, body)`

How will a Pulp-Smash user know that only distribution has this difference?

I suggest that we follow a more Framework'ish thinking and move on to O.O to create entities in Pulp-Smash.

Example:

```python
from pulp_smash.entities import Repo, Distribution, Publication

repo = Repo.create(_generate=True)
distribution = Distribution.create(**body)
publication = Publication.create(repo=repo, ...)
```

Then we can encapsulate the logic behind that `create` (and other CRUD) methods for each of those entities.

It is really  a long term solution that we can work on, but I am concerned on how to solve that problem right now with an easier solution.

I suggest we put a good information on some readme or docs about this change, or even add a `warning` when a `post` request is made directly with the DISTRO_PATH

**Comment by rochacbruno** [comment]
I was thinking if we can `force` the use of this function whenever an `api.post` is made against a distribution, so we keep the same external API

**Comment by rochacbruno** [comment]
Take this example https://github.com/PulpQE/pulp-smash/blob/c199dd183513aa85f2eb1291d0dfdf3d9c5d739e/pulp_smash/api.py#L440
current code
```py
def post(self, url, json=_SENTINEL, **kwargs):
        """Send an HTTP POST request."""
        if json is _SENTINEL:
            return self.request('POST', url, **kwargs)
    return self.request('POST', url, json=json, **kwargs)
```

New:

```py
def post(self, url, json=_SENTINEL, **kwargs):
        """Send an HTTP POST request."""
        if json is _SENTINEL:
            return self.request('POST', url, **kwargs)
    if url in LIST_OF_ASYNC_ENDPOINTS_INCLUDING_DISTRIBUTION:
        return handle_async_response(self.request('POST', url, json=json, **kwargs))
    else:
        return self.request('POST', url, json=json, **kwargs)
```

**Comment by rochacbruno** [comment]
question:

If it returns a `202` why is not being catched by this https://github.com/PulpQE/pulp-smash/blob/c199dd183513aa85f2eb1291d0dfdf3d9c5d739e/pulp_smash/api.py#L78

?

**Comment by kersommoura** [comment]
@rochacbruno, good suggestions. That is why I opened this one as a draft PR.

**Comment by kersommoura** [comment]
closed in favor of https://github.com/PulpQE/pulp-smash/pull/1184

**Pull request closed without merging**
