### PR TITLE
Test actions over a non-existent repository using API.

### PR DESCRIPTION
**Pull request by kersommoura**
Atemmpt to perform the following actions over a non-existent
repository: Sync, Publish, Update and Delete.

In all these actions is expected an exception to be raised. HTTP 4XX.

These actions are testing the failures scenarios mentioned in the
issue #157.

Closes: #157

### CODE REVIEW

**Comment by Ichimonji10** [comment]
A variable on line 226 of module `test_crud` needs to be renamed.

**Comment by kersommoura** [comment]
I noticed that, this is old code. Flake8 is not happy with this name. Variable name is `config`. I changed the name to something else, and it was ok.

**Comment by Ichimonji10** [comment]
> It is strange that did not complaint about it before.

This PR imports the `config` module.

**Comment by Ichimonji10** [comment]
Very good work. Merged, with a follow-up commit of 27f07f8d552bd80eacc699a1ddbd1e2c6ff080b0.

**Pull request merged**
