### PR TITLE
Add UploadSrpmTestCase

### PR DESCRIPTION
**Pull request by Ichimonji10**
This test case verifies that it's possible to upload an SRPM to a
repository.

See: https://github.com/PulpQE/pulp-smash/issues/402

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This test case is basically a copy-paste job of `UploadDrpmTestCase`. I'm not happy about this. But the existing test case also has some definite issues, and the proper solution requires more work than I want to put in right now.

**Comment by Ichimonji10** [comment]
@preethit FYI

**Comment by Ichimonji10** [comment]
Tested against Pulp 2.10 and 2.11:

```console
$ python -m unittest pulp_smash.tests.rpm.api_v2.test_upload_publish.UploadSrpmTestCase
...
----------------------------------------------------------------------
Ran 3 tests in 9.746s

OK
```

**Comment by preethit** [comment]
@Ichimonji10 Awesome!

**Comment by omaciel** [comment]
@Ichimonji10 I don't know what value should be used to import a debug rpm, but if you know the answer to this question, then you could basically have the same test for that content type too :)

**Comment by omaciel** [comment]
@Ichimonji10 https://fedorahosted.org/spacewalk/wiki/DeltaRpmSupport

**Comment by Ichimonji10** [comment]
> @Ichimonji10 I don't know what value should be used to import a debug rpm, but if you know the answer to this question, then you could basically have the same test for that content type too :)

@omaciel A quick look through http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_upload_publish.html shows that we have test cases that upload RPM, DRPM and errata files.

This new test case is basically a copy-paste of `UploadDrpmTestCase`. I'm not happy about the copy-pasta. But there's some other issues with `Upload{Drpm,Srpm}TestCase`, too, and I'd rather get this coverage in now and then both de-duplicate and refactor all together at a later point.

**Comment by Ichimonji10** [comment]
It's also worth noting that the following modules do extensive work with RPMs, SRPMs and DRPMs:

* http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_signatures_saved_for_packages.html
* http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_copies.html
* http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_syncs.html
* http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.rpm.api_v2.test_signatures_checked_for_uploads.html

**Comment by omaciel** [comment]
@Ichimonji10 thanks for the links. I actually wrote my comment while in a meeting, but I then searched for `drpm` and found the tests you mentioned, so... awesome! :)

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
