### PR TITLE
Updating a docker distributor causes an HTTP 500.

### LINKED ISSUE #152: Updating a docker distributor causes an HTTP 500
https://pulp.plan.io/issues/1501
1. create repo, add distributor.
2. update distributor
3. assert update was successful.

### PR DESCRIPTION
**Pull request by ipanova**
fixes #152
Added 3 tests.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
The CI checks fail. Can you update this PR so that they pass? You can verify your changes locally by executing `make all`.

**Comment by ipanova** [comment]
@Ichimonji10 done, sorry for late reply. your message got somehow lost in my mailbox.

**Comment by Ichimonji10** [comment]
No worries about the timeline. We all have plenty of things to keep busy with. :smile:

**Comment by Ichimonji10** [comment]
Merged as d25bbbaf343b66404be261716012d423891ecd0e, with a follow-up commit of 8f1f7c443fe33fd84daa7ecca5faf3521de973e5. Thank you, @ipanova.

**Pull request closed without merging**
