### PR TITLE
Update tests affected by Pulp issue 1332

### PR DESCRIPTION
**Pull request by Ichimonji10**
Pulp issue 1332 [1] describes how searches that attempt to restrict
which fields appear in search results produce malformed results. The
tests for this issue have been blocked for longer than appropriate:
`unittest2.skip` decorators were applied to the relevant test cases
before the current `selectors.bug_is_untestable` function (and other
useful functions in that module) was made available.

Tests results are clean. Tests executed with:

    python -m unittest2 pulp_smash.tests.platform.api_v2.test_search

[1] https://pulp.plan.io/issues/1332

### CODE REVIEW

**Comment by elyezer** [comment]
Pending travis

**Comment by Ichimonji10** [comment]
I've updated the commit message to reflect the change in the Pulp issue.

**Comment by Ichimonji10** [comment]
Pulp 2.8.3:

```
Pulp issue 1332 [1] describes how searches that attempt to restrict
which fields appear in search results produce malformed results. The
tests for this issue have been blocked for longer than appropriate:
`unittest2.skip` decorators were applied to the relevant test cases
before the current `selectors.bug_is_untestable` function (and other
useful functions in that module) was made available.

Tests results are clean. Tests executed with:

    python -m unittest2 pulp_smash.tests.platform.api_v2.test_search

[1] https://pulp.plan.io/issues/1332
```

**Comment by Ichimonji10** [comment]
Thanks for the review, @elyezer. I'll merge when Travis passes.

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
