### PR TITLE
Adding sync and publish tests for python plugin

### PR DESCRIPTION
**Pull request by asmacdo**
Tests for the following changes:
https://github.com/pulp/pulp_python/pull/84

### CODE REVIEW

**Comment by asmacdo** [comment]
requires https://github.com/PulpQE/pulp-fixtures/pull/12 to sync from a repo. To test this locally, you can use change this constant to "pypi.python.org":
https://github.com/PulpQE/pulp-smash/pull/318/files#diff-21d0de1590b3662a6ff25e7cdfe3febdR17

**Comment by Ichimonji10** [comment]
I tested this change by setting each of the following in `pulp_smash/constants.py`, in turn:

```python
PYTHON_FEED_URL = 'https://pypi.python.org'
"""The URL to a Python repository."""

PYTHON_EGG_URL = urljoin(
    PYTHON_FEED_URL,
    'packages/source/s/shelf-reader/shelf-reader-0.1.tar.gz'
)
"""The URL to a Python egg at :data:`PYTHON_FEED_URL`."""
```

(I made some edits to PulpQE/pulp-fixtures#12 and ran `make fixtures/python && python -m http.server` for the following.)

```python
PYTHON_FEED_URL = 'http://localhost:8000/python/fixtures/'
"""The URL to a Python repository."""

PYTHON_EGG_URL = urljoin(
    PYTHON_FEED_URL,
    'packages/source/s/shelf-reader/shelf-reader-0.1.tar.gz'
)
"""The URL to a Python egg at :data:`PYTHON_FEED_URL`."""
```

For each of the above, I ran the following:

```sh
python -m unittest2 pulp_smash.tests.python.api_v2.test_duplicate_uploads
python -m unittest2 pulp_smash.tests.python.api_v2.test_sync_publish
```

Running `test_duplicate_uploads` verifies that I haven't broken `PYTHON_EGG_URL`, and running `test_sync_publish` verifies that the tests in this PR are valid. In both cases, `test_duplicate_uploads` passed. In both cases, `test_sync_publish` failed, with the `self.assertEqual(len(content), 2)` failing.

The Pulp systems used were provisioned just today. If the relevant fix is present in Pulp, the tests should have passed. @asmacdo, is the feature tested by this PR in Pulp yet? And if not, what pulp.plan.io issue tracks this? Remember, failing tests must not be added to Pulp Smash. If you want me to show you how to set up a test environment, just ask. I'll hop on video chat with you and show how.

Also, shouldn't `package_names` be a list, not a single string?

> package_names: This key is a comma separated list of the names of the packages that should be synchronized from the feed URL.

**Comment by Ichimonji10** [comment]
I'm assigning this PR to you, @asmacdo. Please assign to me when the tests are fixed.

**Comment by asmacdo** [comment]
This needs to be run using the fixture added here: https://github.com/PulpQE/pulp-fixtures/pull/22

**Comment by Ichimonji10** [comment]
Merged as a0682303de0e3ccd2ab0f4dcacae4e0962617c77, with a follow-up commit of 0d381841341b958ae23c53487962332845a5b2e7. Thank you, @asmacdo.

**Pull request closed without merging**
