### PR TITLE
Add test for Pulp 2788

### PR DESCRIPTION
**Pull request by Ichimonji10**
The first commit just does some refactoring. The second adds a test case for [Pulp 2788](https://pulp.plan.io/issues/2788).

### CODE REVIEW

**Comment by kersommoura** [comment]
@Ichimonji10, as we talk. Adding a negative test case for ``remove_old_repodata`` as False will improve the test cases covered.

**Comment by Ichimonji10** [comment]
Updated and re-tested.

**Comment by kersommoura** [comment]
@Ichimonji10, with this new change, the test will behave as expected.

**Comment by Ichimonji10** [comment]
Re-tested against beta 3. The test now passes.

**Pull request merged**
